SONAME=libavbin.so.$(AVBIN_VERSION)
LIBNAME=$(OUTDIR)/$(SONAME)

CFLAGS += -fPIC -fno-stack-protector -O3 -m64
LDFLAGS += -shared -soname $(SONAME)

STATIC_LIBS = -whole-archive \
              $(FFMPEG)/libavformat/libavformat.a \
              $(FFMPEG)/libavcodec/libavcodec.a \
              $(FFMPEG)/libavutil/libavutil.a \
              -no-whole-archive

LIBS = 

$(LIBNAME) : $(OBJNAME) $(OUTDIR)
	$(LD) $(LDFLAGS) -o $@ $< $(STATIC_LIBS) $(LIBS)
