LIBNAME=$(OUTDIR)/libavbin.$(AVBIN_VERSION).dylib

CFLAGS += -O3
LDFLAGS += -dylib \
           -read_only_relocs suppress \
		   -single_module

STATIC_LIBS = $(FFMPEG)/libavformat/libavformat.a \
              $(FFMPEG)/libavcodec/libavcodec.a \
              $(FFMPEG)/libavutil/libavutil.a

LIBS = -lSystem \
       -lz \
       -L/usr/lib/gcc/i686-apple-darwin8/4.0.1 -lgcc

$(LIBNAME) : $(OBJNAME) $(OUTDIR)
	$(LD) $(LDFLAGS) -o $@ $< $(STATIC_LIBS) $(LIBS)
